image: rust:1.81.0-alpine

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  MONGODB_URI: "mongodb://db:27017/production"
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  # Enable Rust build caching
  CARGO_INCREMENTAL: 0

# Cache dependencies and build artifacts
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/
    - .cargo/

stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  before_script:
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - cargo clippy
    - cargo fmt -- --check
  # Only store artifacts that are needed for subsequent jobs
  artifacts:
    paths:
      - target/
    expire_in: 1 day

test:
  stage: test
  services:
    - name: mongo:4.4
      alias: db
  before_script:
    - apk add --no-cache musl-dev openssl openssl-dev pkgconfig
  script:
    - APP_ENVIRONMENT=production cargo test

security-audit:
  stage: test
  script:
    - cargo install cargo-audit
    - cargo audit

coverage:
  stage: test
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --out Xml
  coverage: '/(\d+\.?\d*%)/'
