stages:
  - test
  - build
  - deploy

tests:
  stage: test
  image: rust:1.81.0-slim-bullseye
  before_script:
    - apt-get update
    - apt-get install -y pkg-config build-essential libssl-dev

    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - cargo clippy -- --D warnings
    - cargo fmt -- --check
    - cargo test
