variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  RUSTUP_HOME: $CI_PROJECT_DIR/.rustup
  IMAGE_NAME: $DOCKER_HUB_USERNAME/anzar
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA 
  MONGODB_URI: "mongodb://db:27017/test"
  RUST_BACKTRACE: "1"
  RUSTFLAGS: "-D warnings"
  # Enable Rust build caching
  CARGO_INCREMENTAL: 0

# Cache dependencies and build artifacts
cache:
  - key: cargo-tools
    paths:
      - $CARGO_HOME/bin
  - key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target/
      - $CARGO_HOME/registry
      - $RUSTUP_HOME

stages:
  - prepare
  - lint
  - test
  - deploy

prepare:
  image: rust:1.90
  stage: prepare
  script:
    - rustup default stable
    - rustup component add rustfmt clippy
    - cargo build --release        # ← build ONCE here
    - cargo test --no-run          # ← compile tests without running them
  artifacts:
    paths:
      - target/
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_TAG

lint:
  image: rust:1.90
  stage: lint
  allow_failure: true
  needs:
    - job: prepare
      artifacts: true
  script:
    - cargo fmt -- --check
    - cargo clippy
  rules:
    - if: $CI_COMMIT_TAG

test:
  image: rust:1.90
  stage: test
  needs:
    - job: prepare
      artifacts: true
  services:
    - name: mongo:4.4
      alias: db
  script:
    - ENV=prod cargo test --jobs $(nproc)
    # - cargo tarpaulin --version || cargo install cargo-tarpaulin
    # - cargo tarpaulin --ignore-tests 
  rules:
    - if: $CI_COMMIT_TAG
security-audit:
  image: rust:1.90
  stage: test
  allow_failure: true
  needs:
    - job: prepare
      artifacts: true
  script:
    - cargo audit --version || cargo install cargo-audit
    - cargo audit --deny warnings
  rules:
    - if: $CI_COMMIT_TAG


build:
  image: docker:24
  stage: deploy
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  rules:
    - if: $CI_COMMIT_TAG
