image: rust:1.85.0

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  RUSTUP_HOME: $CI_PROJECT_DIR/.rustup
  MONGODB_URI: "mongodb://db:27017/production"
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  # Enable Rust build caching
  CARGO_INCREMENTAL: 1

# Cache dependencies and build artifacts
cache:
  - key: cargo-tools
    paths:
      - $CARGO_HOME/bin
  - key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target/
      - $CARGO_HOME/registry
      - $RUSTUP_HOME

stages:
  - lint
  - test
  - build
  - deploy


lint:
  stage: lint
  before_script:
    - rustup default stable
    - rustup component add rustfmt clippy
  script:
    - cargo fmt -- --check
    - cargo clippy

test:
  stage: test
  services:
    - name: mongo:4.4
      alias: db
  script:
    - APP_ENVIRONMENT=production cargo test --jobs $(nproc)
    - if ! command -v cargo-tarpaulin &> /dev/null; then cargo install cargo-tarpaulin; fi
    - cargo tarpaulin --ignore-tests 
security-audit:
  stage: test
  allow_failure: true
  script:
    - if ! command -v cargo-audit &> /dev/null; then cargo install --locked cargo-audit; fi
    - cargo audit --deny warnings


build:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/anzar
    expire_in: 1 day
