image: rust:1.85.0

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  RUSTUP_HOME: $CI_PROJECT_DIR/.rustup
  MONGODB_URI: "mongodb://db:27017/production"
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  # Enable Rust build caching
  CARGO_INCREMENTAL: 1

# Cache dependencies and build artifacts
cache:
  - key: cargo-tools
    paths:
      - $CARGO_HOME/bin
  - key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target/
      - $CARGO_HOME/registry
      - $RUSTUP_HOME

stages:
  - prepare
  - lint
  - test
  - build
  - deploy

prepare:
  stage: prepare
  script:
    - rustup default stable
    - rustup component add rustfmt clippy
    - cargo build --tests
  artifacts:
    paths:
      - target/
    expire_in: 1 week

lint:
  stage: lint
  dependencies:
    - prepare
  script:
    - cargo fmt -- --check
    - cargo clippy

test:
  stage: test
  dependencies:
    - prepare
  services:
    - name: mongo:4.4
      alias: db
  script:
    - APP_ENVIRONMENT=production cargo test --jobs $(nproc)
    # - cargo tarpaulin --version || cargo install cargo-tarpaulin
    # - cargo tarpaulin --ignore-tests 
security-audit:
  stage: test
  allow_failure: true
  script:
    - cargo audit --version || cargo install cargo-audit
    - cargo audit --deny warnings


# build:
#   stage: build
#   dependencies:
#     - prepare
#   script:
#     - cargo build --release
#   artifacts:
#     paths:
#       - target/release/anzar
#     expire_in: 1 day
