image: rust:1.85.0

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  MONGODB_URI: "mongodb://db:27017/production"
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  # Enable Rust build caching
  CARGO_INCREMENTAL: 0

# Cache dependencies and build artifacts
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/
    - .cargo/

stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy
  # Only store artifacts that are needed for subsequent jobs
  artifacts:
    paths:
      - target/
    expire_in: 1 day

test:
  stage: test
  services:
    - name: mongo:4.4
      alias: db
  script:
    - APP_ENVIRONMENT=production cargo test
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --ignore-tests 

security-audit:
  stage: test
  script:
    - cargo install cargo-audit
    - cargo audit
