port: 3000
database:
  port: 27017
  # host: "db" # name <db> found in docker compsoe file
  host: "localhost" # name <db> found in docker compsoe file
  username: "hakou"
  password: "hakou"
  database_name: "dev"
